--------------------------------------------------------------
--------------------------------------------------------------
--                                                          --
-- This VHDL file has been generated by the verilog2vhdl    --
-- tool.                                                    --
-- Contact help@edautils.com  for support/info.--
--                                                          --
--                                                          --
--------------------------------------------------------------
--------------------------------------------------------------
--
--
-- Assumptions: 
--         (1) All the parameters are of type INTEGER, and hence the translated generics are of this type
--
--
-- Generated by : apache on 11/1/21 2:20 AM
--
--
library ieee;
use ieee.std_logic_1164.all;
package vl2vh_common_pack is 
    type vl2vh_memory_type is      array  ( natural range <> , natural range <>  )  of std_logic ;
    function vl2vh_ternary_func(  constant cond : Boolean;  constant trueval : std_logic;  constant falseval : std_logic)  return std_logic; 
    function vl2vh_ternary_func(  constant cond : Boolean;  constant trueval : std_logic_vector;  constant falseval : std_logic_vector)  return std_logic_vector; 
end package; 




package body vl2vh_common_pack is 
    function vl2vh_ternary_func(  constant cond : Boolean;  constant trueval : std_logic;  constant falseval : std_logic)  return std_logic is 
    begin
        if ( cond ) then 
             return trueval;
        else 
             return falseval;
        end if;
    end;
    function vl2vh_ternary_func(  constant cond : Boolean;  constant trueval : std_logic_vector;  constant falseval : std_logic_vector)  return std_logic_vector is 
    begin
        if ( cond ) then 
             return trueval;
        else 
             return falseval;
        end if;
    end;
end; 


library ieee;
library work;
use ieee.std_logic_1164.all;
use ieee.std_logic_misc.all;
use ieee.numeric_std.all;
use work.vl2vh_common_pack.all;
entity CPU is 
     port (
        Clock :  inout std_logic;
        DataIn :  inout std_logic_vector( 9  downto 0  );
        DataOut :  inout std_logic_vector( 9  downto 0  )
    );
end entity; 


architecture rtl of CPU is 
    begin 
    end; 


library ieee;
library work;
use ieee.std_logic_1164.all;
use ieee.std_logic_misc.all;
use ieee.numeric_std.all;
use work.vl2vh_common_pack.all;
entity testbench is 
end entity; 


architecture rtl of testbench is 
    signal Clock : std_logic := 0 ;
    signal DataIn : std_logic_vector( 9  downto 0  ) := 10 ;
    signal DataOut : std_logic_vector( 9  downto 0  );
    component CPU is 
         port (
            Clock :  inout std_logic;
            DataIn :  inout std_logic_vector( 9  downto 0  );
            DataOut :  inout std_logic_vector( 9  downto 0  )
        );
    end component; 
    begin 
        process 
        begin
            wait for 10  ns;
            Clock <= (  not Clock ) ;
        end process;
        inst : CPU
            port map (
                Clock => Clock,
                DataIn => DataIn,
                DataOut => DataOut
                );
    end; 


