#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Nov 16 20:00:14 PST 2021
# SW Build 3286242 on Wed Jul 28 13:09:46 MDT 2021
#
# IP Build 3279568 on Wed Jul 28 16:48:48 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim testbench_behav -key {Behavioral:sim_1:Functional:testbench} -tclbatch testbench.tcl -log simulate.log"
xsim testbench_behav -key {Behavioral:sim_1:Functional:testbench} -tclbatch testbench.tcl -log simulate.log

