# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sida/workspace/local.sida.com/class247/project/cs247/cs247.srcs/sources_1/ip/ProgramMemory_1/ProgramMemory.xci
# IP: The module: 'ProgramMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sida/workspace/local.sida.com/class247/project/cs247/cs247.gen/sources_1/ip/ProgramMemory_1/ProgramMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ProgramMemory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sida/workspace/local.sida.com/class247/project/cs247/cs247.srcs/sources_1/ip/ProgramMemory_1/ProgramMemory.xci
# IP: The module: 'ProgramMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sida/workspace/local.sida.com/class247/project/cs247/cs247.gen/sources_1/ip/ProgramMemory_1/ProgramMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ProgramMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
